endpoints: 
  restart: 
    enabled: true
files: 
  catalog-rule:
    dir-path: E:\\git-repo\\simple-spring-boot-rules-engine\\rules\\
    name: rules_catalog.json
  service-call: 
    dir-path: E:\\git-repo\\simple-spring-boot-rules-engine\\services\\
    name: service_catalog.json
management: 
  security: 
    enabled: false
security: 
  basic: 
    enabled: false
  ignored: /swagger-resources/**
server: 
  port: 8080
spring: 
  application: 
    name: rulesengine
  endpoints: 
    enabled-by-default: true
    web: 
      exposure: 
        include: "*"